-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_name character varying NOT NULL,
  org_code character varying NOT NULL UNIQUE,
  address text,
  contact_email character varying,
  contact_phone character varying,
  subscription_tier character varying DEFAULT 'basic'::character varying,
  subscription_expiry date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  site_name character varying NOT NULL,
  address text,
  contact_person character varying,
  contact_phone character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sites_pkey PRIMARY KEY (id),
  CONSTRAINT sites_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  organization_id uuid,
  site_id uuid,
  parent_admin_id uuid,
  full_name character varying,
  email character varying,
  phone character varying,
  user_type character varying DEFAULT 'guard'::character varying,
  can_manage_devices boolean DEFAULT false,
  can_view_all_sites boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_super_admin boolean DEFAULT false,
  pin character varying,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT profiles_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT profiles_parent_admin_id_fkey FOREIGN KEY (parent_admin_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  device_id character varying NOT NULL UNIQUE,
  device_name character varying,
  device_description text,
  serial_number character varying,
  model character varying,
  os_version character varying,
  app_version character varying,
  battery_level integer,
  memory_available_percent integer,
  storage_available_percent integer,
  license_expiry date,
  latest_sync_update timestamp with time zone,
  next_cloud_sync timestamp with time zone,
  upload_to_cloud boolean DEFAULT true,
  last_restart timestamp with time zone,
  app_started_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  site_bound_at timestamp with time zone,
  site_bound_by uuid,
  CONSTRAINT devices_pkey PRIMARY KEY (id),
  CONSTRAINT devices_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT devices_site_bound_by_fkey FOREIGN KEY (site_bound_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.device_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid,
  site_id uuid,
  lock_mode character varying DEFAULT 'unlocked'::character varying,
  allow_whatsapp boolean DEFAULT false,
  initialize_nfc boolean DEFAULT false,
  nfc_startup_delay integer DEFAULT 0,
  data_retention_period integer DEFAULT 6,
  auto_exit_vehicle boolean DEFAULT false,
  upload_vehicle_image boolean DEFAULT false,
  upload_enter_driver_image boolean DEFAULT false,
  upload_exit_driver_image boolean DEFAULT false,
  auto_exit_pedestrian boolean DEFAULT false,
  upload_pedestrian_image boolean DEFAULT false,
  upload_pedestrian_id_image boolean DEFAULT false,
  ptt_on_off boolean DEFAULT false,
  ptt_only_after_login boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  auto_close_shift_at_midnight boolean DEFAULT false,
  allow_quick_guard_switch boolean DEFAULT false,
  CONSTRAINT device_settings_pkey PRIMARY KEY (id),
  CONSTRAINT device_settings_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id),
  CONSTRAINT device_settings_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  device_id uuid,
  guard_id uuid,
  shift_name character varying,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  local_guard_id uuid,
  end_reason text,
  CONSTRAINT shifts_pkey PRIMARY KEY (id),
  CONSTRAINT shifts_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT shifts_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id),
  CONSTRAINT shifts_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.profiles(id),
  CONSTRAINT shifts_local_guard_id_fkey FOREIGN KEY (local_guard_id) REFERENCES public.guards(id)
);
CREATE TABLE public.incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  shift_id uuid,
  reported_by uuid,
  incident_type character varying,
  description text,
  severity character varying DEFAULT 'low'::character varying,
  reported_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'open'::character varying,
  location text,
  guard_id uuid,
  resolved boolean DEFAULT false,
  local_guard_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  device_id uuid,
  picture_url text,
  photo_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT incidents_pkey PRIMARY KEY (id),
  CONSTRAINT incidents_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT incidents_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT incidents_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.profiles(id),
  CONSTRAINT incidents_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES auth.users(id),
  CONSTRAINT incidents_local_guard_id_fkey FOREIGN KEY (local_guard_id) REFERENCES public.guards(id),
  CONSTRAINT incidents_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  shift_id uuid,
  license_plate character varying,
  vehicle_type character varying,
  driver_name character varying,
  entered_at timestamp with time zone DEFAULT now(),
  exited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  vehicle_make text,
  vehicle_color text,
  visiting_unit text,
  guard_id uuid,
  driver_contact text,
  visitor_type character varying,
  local_guard_id uuid,
  picture_url text,
  deleted_at timestamp with time zone,
  device_id uuid,
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT vehicles_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT vehicles_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES auth.users(id),
  CONSTRAINT vehicles_local_guard_id_fkey FOREIGN KEY (local_guard_id) REFERENCES public.guards(id),
  CONSTRAINT vehicles_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id)
);
CREATE TABLE public.pedestrians (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  shift_id uuid,
  full_name character varying,
  id_number character varying,
  exited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  contact_number text,
  visiting_unit text,
  host_name text,
  purpose_of_visit text,
  guard_id uuid,
  entry_time timestamp with time zone DEFAULT now(),
  exit_time timestamp with time zone,
  is_precleared boolean DEFAULT false,
  local_guard_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  picture_url text,
  deleted_at timestamp with time zone,
  device_id uuid,
  CONSTRAINT pedestrians_pkey PRIMARY KEY (id),
  CONSTRAINT pedestrians_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT pedestrians_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT pedestrians_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES auth.users(id),
  CONSTRAINT pedestrians_local_guard_id_fkey FOREIGN KEY (local_guard_id) REFERENCES public.guards(id),
  CONSTRAINT pedestrians_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id)
);
CREATE TABLE public.ob_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  shift_id uuid,
  captured_by uuid,
  entry_text text,
  captured_timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  serial_number character varying UNIQUE,
  nature_of_occurrence text,
  guard_id uuid,
  local_guard_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  device_id uuid,
  CONSTRAINT ob_entries_pkey PRIMARY KEY (id),
  CONSTRAINT ob_entries_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT ob_entries_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT ob_entries_captured_by_fkey FOREIGN KEY (captured_by) REFERENCES public.profiles(id),
  CONSTRAINT ob_entries_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES auth.users(id),
  CONSTRAINT ob_entries_local_guard_id_fkey FOREIGN KEY (local_guard_id) REFERENCES public.guards(id),
  CONSTRAINT ob_entries_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id)
);
CREATE TABLE public.device_sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid,
  sync_type character varying,
  sync_status character varying,
  records_synced integer,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT device_sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT device_sync_logs_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id)
);
CREATE TABLE public.patrols (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  shift_id uuid,
  patrol_name character varying,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying,
  steps_taken integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  guard_id uuid,
  local_guard_id uuid,
  deleted_at timestamp with time zone,
  device_id uuid,
  CONSTRAINT patrols_pkey PRIMARY KEY (id),
  CONSTRAINT patrols_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT patrols_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT patrols_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES auth.users(id),
  CONSTRAINT patrols_local_guard_id_fkey FOREIGN KEY (local_guard_id) REFERENCES public.guards(id),
  CONSTRAINT patrols_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id)
);
CREATE TABLE public.patrol_checkpoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patrol_id uuid,
  name character varying,
  checkpoint_order integer,
  latitude numeric,
  longitude numeric,
  scanned_at timestamp with time zone,
  scanned_by uuid,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  tag_uid character varying,
  site_id uuid,
  zone character varying,
  required boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patrol_checkpoints_pkey PRIMARY KEY (id),
  CONSTRAINT patrol_checkpoints_patrol_id_fkey FOREIGN KEY (patrol_id) REFERENCES public.patrols(id),
  CONSTRAINT patrol_checkpoints_scanned_by_fkey FOREIGN KEY (scanned_by) REFERENCES public.profiles(id),
  CONSTRAINT patrol_checkpoints_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  shift_id uuid,
  delivery_time timestamp with time zone DEFAULT now(),
  recipient_name character varying,
  recipient_contact character varying,
  unit character varying,
  issuer_name character varying,
  exchange_details text,
  picture_url text,
  signature_url text,
  pdf_url text,
  recorded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT deliveries_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT deliveries_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT deliveries_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.wheel_clamps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  shift_id uuid,
  vehicle_registration character varying,
  offender_name character varying,
  offender_type character varying,
  unit character varying,
  clamped_at timestamp with time zone DEFAULT now(),
  removed_at timestamp with time zone,
  picture_url text,
  signature_url text,
  pdf_url text,
  clamped_by uuid,
  removed_by uuid,
  status character varying DEFAULT 'clamped'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT wheel_clamps_pkey PRIMARY KEY (id),
  CONSTRAINT wheel_clamps_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT wheel_clamps_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT wheel_clamps_clamped_by_fkey FOREIGN KEY (clamped_by) REFERENCES public.profiles(id),
  CONSTRAINT wheel_clamps_removed_by_fkey FOREIGN KEY (removed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.dockets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  incident_id uuid,
  docket_number character varying NOT NULL UNIQUE,
  investigator uuid,
  client_name character varying,
  details text,
  pdf_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT dockets_pkey PRIMARY KEY (id),
  CONSTRAINT dockets_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES public.incidents(id),
  CONSTRAINT dockets_investigator_fkey FOREIGN KEY (investigator) REFERENCES public.profiles(id)
);
CREATE TABLE public.device_patrol_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid,
  shift_id uuid,
  patrol_id uuid,
  steps_since_patrol_start integer DEFAULT 0,
  steps_since_last_scan integer DEFAULT 0,
  gps_accuracy numeric,
  route_name character varying,
  time_left interval,
  status character varying DEFAULT 'in_progress'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT device_patrol_data_pkey PRIMARY KEY (id),
  CONSTRAINT device_patrol_data_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id),
  CONSTRAINT device_patrol_data_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT device_patrol_data_patrol_id_fkey FOREIGN KEY (patrol_id) REFERENCES public.patrols(id)
);
CREATE TABLE public.nfc_scans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  guard_id uuid,
  shift_id uuid,
  patrol_id uuid,
  checkpoint_id uuid,
  checkpoint_name character varying,
  tag_uid character varying,
  scanned_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'matched'::character varying,
  local_guard_id uuid,
  latitude double precision,
  longitude double precision,
  location_accuracy double precision,
  method text,
  device_id uuid,
  CONSTRAINT nfc_scans_pkey PRIMARY KEY (id),
  CONSTRAINT nfc_scans_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT nfc_scans_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES auth.users(id),
  CONSTRAINT nfc_scans_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT nfc_scans_patrol_id_fkey FOREIGN KEY (patrol_id) REFERENCES public.patrols(id),
  CONSTRAINT nfc_scans_local_guard_id_fkey FOREIGN KEY (local_guard_id) REFERENCES public.guards(id),
  CONSTRAINT nfc_scans_checkpoint_id_fkey FOREIGN KEY (checkpoint_id) REFERENCES public.patrol_checkpoints(id),
  CONSTRAINT nfc_scans_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id)
);
CREATE TABLE public.site_lookup_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid UNIQUE,
  shift_options ARRAY,
  pedestrian_types ARRAY,
  vehicle_types ARRAY,
  units ARRAY,
  incident_types ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_lookup_data_pkey PRIMARY KEY (id),
  CONSTRAINT site_lookup_data_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.site_patrol_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid UNIQUE,
  patrol_interval_minutes integer DEFAULT 60,
  required_nfc_tags_count integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patrol_times jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT site_patrol_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT site_patrol_schedules_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.report_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  report_type character varying DEFAULT 'pedestrian'::character varying,
  send_time_utc time without time zone,
  subject_line character varying,
  recipient_emails ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT report_schedules_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.guards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  organization_id uuid,
  full_name character varying NOT NULL,
  pin character varying,
  badge_number character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT guards_pkey PRIMARY KEY (id),
  CONSTRAINT guards_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.app_notification_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id text,
  guard_id uuid,
  shift_id uuid,
  patrol_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  occurred_at timestamp with time zone NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_notification_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id text,
  guard_id uuid,
  shift_id uuid,
  type text NOT NULL,
  severity text NOT NULL DEFAULT 'info'::text,
  occurred_at timestamp with time zone NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ota_channels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ota_channels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ota_bundles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  channel_id uuid NOT NULL,
  version character varying NOT NULL,
  storage_path text NOT NULL,
  checksum character varying,
  size_bytes bigint,
  release_notes text,
  min_native_version character varying,
  is_active boolean NOT NULL DEFAULT true,
  is_mandatory boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ota_bundles_pkey PRIMARY KEY (id),
  CONSTRAINT ota_bundles_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.ota_channels(id)
);
CREATE TABLE public.org_ota_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  channel_id uuid NOT NULL,
  pinned_version character varying,
  auto_update boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_ota_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT org_ota_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT org_ota_assignments_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.ota_channels(id)
);
CREATE TABLE public.ota_update_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id character varying,
  organization_id uuid,
  bundle_id uuid,
  from_version character varying,
  to_version character varying,
  status character varying NOT NULL,
  error_message text,
  native_version character varying,
  platform character varying,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ota_update_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ota_update_logs_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES public.ota_bundles(id)
);
CREATE TABLE public.ota_device_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id character varying NOT NULL UNIQUE,
  channel_id uuid NOT NULL,
  pinned_version character varying,
  auto_update boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ota_device_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT ota_device_assignments_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.ota_channels(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id text NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['update'::text, 'delete'::text, 'restore'::text])),
  actor_id uuid,
  actor_email text,
  site_id uuid,
  record_label text,
  changes jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profile_sites (
  profile_id uuid NOT NULL,
  site_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profile_sites_pkey PRIMARY KEY (profile_id, site_id),
  CONSTRAINT profile_sites_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT profile_sites_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.device_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id text NOT NULL,
  site_id uuid,
  recorded_at timestamp with time zone NOT NULL,
  latitude double precision NOT NULL CHECK (latitude >= '-90'::integer::double precision AND latitude <= 90::double precision),
  longitude double precision NOT NULL CHECK (longitude >= '-180'::integer::double precision AND longitude <= 180::double precision),
  accuracy real,
  battery_level smallint CHECK (battery_level IS NULL OR battery_level >= 0 AND battery_level <= 100),
  source text NOT NULL DEFAULT 'background'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT device_locations_pkey PRIMARY KEY (id),
  CONSTRAINT device_locations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.report_recipients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL UNIQUE,
  recipient_emails ARRAY NOT NULL DEFAULT '{}'::text[],
  immediate_emails ARRAY NOT NULL DEFAULT '{}'::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  daily_send_time time without time zone,
  CONSTRAINT report_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT report_recipients_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.report_deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid,
  report_type text NOT NULL,
  trigger_kind text NOT NULL,
  source_id uuid,
  recipients ARRAY NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL,
  skip_reason text,
  provider_message_id text,
  error text,
  row_count integer,
  period_start timestamp with time zone,
  period_end timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT report_deliveries_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.report_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  company_name text NOT NULL DEFAULT 'NightGuard'::text,
  psira_number text,
  registration_number text,
  vat_number text,
  address_line text,
  phone text,
  contact_email text,
  footer_note text,
  logo_data_url text,
  brand_color text NOT NULL DEFAULT '#c8000a'::text,
  from_email text NOT NULL DEFAULT 'onboarding@resend.dev'::text,
  from_name text NOT NULL DEFAULT 'NightGuard Reports'::text,
  reply_to text,
  timezone text NOT NULL DEFAULT 'Africa/Johannesburg'::text,
  daily_send_time time without time zone NOT NULL DEFAULT '06:00:00'::time without time zone,
  emails_enabled boolean NOT NULL DEFAULT false,
  daily_incident_enabled boolean NOT NULL DEFAULT true,
  daily_patrol_enabled boolean NOT NULL DEFAULT true,
  daily_entry_exit_enabled boolean NOT NULL DEFAULT true,
  immediate_incident_enabled boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_settings_pkey PRIMARY KEY (id)
);